//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestExams.Translation {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestExams.Translation.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string Btn_InicioSesion {
            get {
                return ResourceManager.GetString("Btn_InicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar contraseña.
        /// </summary>
        public static string Btn_PassLost {
            get {
                return ResourceManager.GetString("Btn_PassLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string Btn_signIn {
            get {
                return ResourceManager.GetString("Btn_signIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Castellano.
        /// </summary>
        public static string CbI_Castellano {
            get {
                return ResourceManager.GetString("CbI_Castellano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asturiano.
        /// </summary>
        public static string Cbl_Asturianu {
            get {
                return ResourceManager.GetString("Cbl_Asturianu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, existe un usuario con el mismo correo.
        /// </summary>
        public static string Error_MailRepeat {
            get {
                return ResourceManager.GetString("Error_MailRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, existe una asignatura con el mismo nombre.
        /// </summary>
        public static string Error_SubjetRepeat {
            get {
                return ResourceManager.GetString("Error_SubjetRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, existe un tema con el mismo nombre..
        /// </summary>
        public static string Error_ThemeRepeat {
            get {
                return ResourceManager.GetString("Error_ThemeRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, el usuario no se puede borrar porque está siendo usado.
        /// </summary>
        public static string Error_UserInUse {
            get {
                return ResourceManager.GetString("Error_UserInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, el usuario no existe.
        /// </summary>
        public static string Error_UserNotFound {
            get {
                return ResourceManager.GetString("Error_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, existe un usuario con el mismo nombre.
        /// </summary>
        public static string Error_UserRepeat {
            get {
                return ResourceManager.GetString("Error_UserRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración de idioma.
        /// </summary>
        public static string Lab_LenguajeSettings {
            get {
                return ResourceManager.GetString("Lab_LenguajeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione su idioma:.
        /// </summary>
        public static string Lab_SelectLenguaje {
            get {
                return ResourceManager.GetString("Lab_SelectLenguaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca su usuario y contraseña:.
        /// </summary>
        public static string lab_sesion {
            get {
                return ResourceManager.GetString("lab_sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La asignatura se ha añadido correctamente.
        /// </summary>
        public static string Message_AddSubjetOk {
            get {
                return ResourceManager.GetString("Message_AddSubjetOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tema se ha añadido correctamente..
        /// </summary>
        public static string Message_AddThemeOk {
            get {
                return ResourceManager.GetString("Message_AddThemeOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se ha añadido correctamente.
        /// </summary>
        public static string Message_AddUserOk {
            get {
                return ResourceManager.GetString("Message_AddUserOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La asignatura se ha borrado correctamente.
        /// </summary>
        public static string Message_RemoveSubjetOk {
            get {
                return ResourceManager.GetString("Message_RemoveSubjetOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se ha borrado correctamente.
        /// </summary>
        public static string Message_RemoveUserOk {
            get {
                return ResourceManager.GetString("Message_RemoveUserOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no esta en uso.
        /// </summary>
        public static string Message_UserNotInUse {
            get {
                return ResourceManager.GetString("Message_UserNotInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string Tile_Config {
            get {
                return ResourceManager.GetString("Tile_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exámenes.
        /// </summary>
        public static string Tile_Examen {
            get {
                return ResourceManager.GetString("Tile_Examen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión.
        /// </summary>
        public static string Title_Session {
            get {
                return ResourceManager.GetString("Title_Session", resourceCulture);
            }
        }
    }
}
